### ISSUE TITLE
Design and create menu UI and add navigational functions (back buttons) with start, options, leaderboard and quit buttons

### ISSUE THREAD

**Issue by samwj02** [SophiesGames/SussexGamesRepo#18]

**Comment by samwj02** [comment]
![Menu mockup 1](https://user-images.githubusercontent.com/43371252/62048330-81df0200-b204-11e9-9f92-53d84e68a300.JPG)

**Comment by samwj02** [comment]
![image](https://user-images.githubusercontent.com/43371252/62048347-93280e80-b204-11e9-9b0c-b656afde154a.png)

Menu mockup 1

**Comment by samwj02** [comment]
![Menu mockup 2](https://user-images.githubusercontent.com/43371252/62421160-45445800-b695-11e9-82c5-1c51666dd227.png)

Menu mockup 2

**Comment by samwj02** [comment]
![Menu mockup 2](https://user-images.githubusercontent.com/43371252/62427081-2c639300-b6e5-11e9-9723-bab78cf3b8f2.png)

Menu Mockup 2 with minor updates

**Comment by samwj02** [comment]
Incorporate the above menu designs into the game, for now just need "PLAY" and "WUIT GAME", leave spaces for the other buttons.

**Comment by samwj02** [comment]
Display timer when playing game, when the player lose the last time is displayed.

**Comment by Hellbinder1** [comment]
Create an options screen

**Comment by samwj02** [comment]
![image](https://user-images.githubusercontent.com/43371252/64487839-84873b00-d237-11e9-9561-e4d60c25ae14.png)

Final placeholder, will be replaced with Kieron's art later
